# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
  - julia: nightly

env:
  - PYTHON=""

notifications:
  email: false

before_install:
  # Prevent failure because conda up-/downgrades Python after installing PyCall 
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("cvxopt")'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CVXOPT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
